name: imc-ste
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch==2.6.0
      - torchvision==0.21.0
      - numpy==1.26.4
      - Pillow==12.1.1
      - matplotlib==3.10.8
      - scipy==1.15.2
      - PyYAML==6.0.3
      - pytest==9.0.3
      - -e .
