#!/usr/bin/env python3
"""Build a compact, auditable submission ZIP from a strict allowlist."""

from __future__ import annotations

import argparse
import csv
import hashlib
import io
import json
import re
import zipfile
from datetime import datetime, timezone
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = PROJECT_ROOT / "dist" / "imc_ste_challenge_submission.zip"
DEFAULT_MANIFEST_OUTPUT = PROJECT_ROOT / "dist" / "submission_manifest.csv"
ROOT_FILES = (
    ".gitignore",
    ".submissionignore",
    "README.md",
    "environment.yml",
    "pyproject.toml",
)
DOC_FILES = (
    "docs/algorithm_architecture_and_workflow.md",
    "docs/final_report.md",
    "docs/submission_readme.md",
    "docs/theory_and_complexity.md",
    "docs/generated/key_results.md",
    "docs/diagrams/algorithm_architecture.dot",
    "docs/diagrams/training_workflow.dot",
    "docs/diagrams/Makefile",
)
PAPER_FILES = (
    "paper/main.tex",
    "paper/main.pdf",
    "paper/references.bib",
    "paper/README.md",
    "paper/Makefile",
)
SOURCE_TREES = ("src", "scripts", "tests", "configs")
RESULT_FILES = (
    "runs/main_uniform_noise_summary.csv",
    "runs/tinyimagenet_imagenet224_summary.csv",
    "runs/tinyimagenet_efficientnet_b0_clean_layer_noise_decomposition_seed1.csv",
    "runs/tinyimagenet_efficientnet_b0_activation_preconditioning_summary.csv",
    "runs/statistical_summary.csv",
    "runs/statistical_pairwise_comparisons.csv",
    "runs/statistical_anova.csv",
    "runs/tool_sanity_check.csv",
    "runs/optional_full_validation_summary.csv",
    "runs/optional_paired_extension_summary.csv",
    "runs/optional_full_epoch_extension.csv",
    "runs/efficiency_benchmark.csv",
    "runs/efficiency_benchmark_metadata.json",
    "runs/submission_key_results.csv",
)
PUBLIC_MARKDOWN_FILES = (
    "README.md",
    "docs/algorithm_architecture_and_workflow.md",
    "docs/final_report.md",
    "docs/submission_readme.md",
    "docs/theory_and_complexity.md",
    "docs/generated/key_results.md",
    "paper/README.md",
)
PUBLIC_TEXT_FILES = PUBLIC_MARKDOWN_FILES + (
    "paper/main.tex",
    "paper/references.bib",
)
FORBIDDEN_SUFFIXES = {".pt", ".pth", ".ckpt", ".jsonl", ".pyc"}
FORBIDDEN_PARTS = {"data", "__pycache__", ".pytest_cache", "dist", "build"}
FORBIDDEN_RELEASE_DOCUMENTS = {
    "final_report_draft.md",
    "report_notes.md",
    "research_plan.md",
    "submission_checklist.md",
}
FORBIDDEN_RELEASE_MARKERS = (
    "codex",
    "chatgpt",
    "openai",
    "generated by ai",
    "ai-generated",
    "todo",
    "fixme",
    "工作底稿",
    "报告草稿",
    "思考过程",
    "中间思考",
    "作者与所属单位暂时留空",
    "authors and affiliations are intentionally blank",
    "report_notes.md",
    "research_plan.md",
    "submission_checklist.md",
    "final_report_draft.md",
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", type=Path, default=PROJECT_ROOT)
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
    )
    parser.add_argument(
        "--manifest-output",
        type=Path,
        default=DEFAULT_MANIFEST_OUTPUT,
    )
    parser.add_argument("--root-name", default="imc_ste_challenge")
    parser.add_argument("--max-mib", type=float, default=100.0)
    parser.add_argument(
        "--documents-only",
        action="store_true",
        help="build a documentation, paper, figure, and canonical-results archive",
    )
    return parser.parse_args()


def digest_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def digest_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def validate_relative(relative: Path) -> None:
    if relative.is_absolute() or ".." in relative.parts:
        raise ValueError(f"unsafe package path: {relative}")
    if any(part in FORBIDDEN_PARTS for part in relative.parts):
        raise ValueError(f"forbidden package directory: {relative}")
    if relative.suffix.lower() in FORBIDDEN_SUFFIXES:
        raise ValueError(f"forbidden package file type: {relative}")


def add_file(
    entries: dict[str, tuple[Path, str]],
    project_root: Path,
    relative: str | Path,
    category: str,
) -> None:
    relative_path = Path(relative)
    validate_relative(relative_path)
    path = project_root / relative_path
    if not path.is_file():
        raise FileNotFoundError(f"allowlisted package file is missing: {relative_path}")
    entries[relative_path.as_posix()] = (path, category)


def validate_release_text(project_root: Path) -> None:
    for relative in PUBLIC_TEXT_FILES:
        path = project_root / relative
        if not path.is_file():
            raise FileNotFoundError(f"release text file is missing: {relative}")
        folded = path.read_text(encoding="utf-8").casefold()
        matches = [marker for marker in FORBIDDEN_RELEASE_MARKERS if marker.casefold() in folded]
        if matches:
            raise ValueError(
                f"release text contains internal marker(s) in {relative}: "
                + ", ".join(matches)
            )


def referenced_figure_files(project_root: Path) -> set[Path]:
    names: set[str] = set()
    for relative in PUBLIC_MARKDOWN_FILES:
        text = (project_root / relative).read_text(encoding="utf-8")
        names.update(re.findall(r"figures/([A-Za-z0-9_.-]+)", text))

    paper = (project_root / "paper" / "main.tex").read_text(encoding="utf-8")
    names.update(
        re.findall(r"\\includegraphics(?:\[[^]]*\])?\{([A-Za-z0-9_.-]+)\}", paper)
    )
    return {Path("docs") / "figures" / name for name in names}


def validate_public_references(
    project_root: Path, entries: dict[str, tuple[Path, str]]
) -> None:
    missing: list[str] = []
    for relative in PUBLIC_MARKDOWN_FILES:
        text = (project_root / relative).read_text(encoding="utf-8")
        for name in re.findall(r"runs/([A-Za-z0-9_.-]+\.(?:csv|json))", text):
            result = (Path("runs") / name).as_posix()
            if result not in entries:
                missing.append(f"{relative} -> {result}")
    if missing:
        raise FileNotFoundError(
            "public documentation references unpackaged result files: "
            + ", ".join(missing)
        )


def collect_entries(
    project_root: Path, *, documents_only: bool = False
) -> dict[str, tuple[Path, str]]:
    validate_release_text(project_root)
    entries: dict[str, tuple[Path, str]] = {}
    root_files = ("README.md",) if documents_only else ROOT_FILES
    for relative in root_files:
        add_file(entries, project_root, relative, "project")
    for relative in DOC_FILES:
        add_file(entries, project_root, relative, "documentation")
    for relative in PAPER_FILES:
        add_file(entries, project_root, relative, "paper")

    if not documents_only:
        for tree in SOURCE_TREES:
            root = project_root / tree
            if not root.is_dir():
                raise FileNotFoundError(f"missing source tree: {tree}")
            for path in sorted(root.rglob("*")):
                if not path.is_file():
                    continue
                relative = path.relative_to(project_root)
                if any(part in FORBIDDEN_PARTS for part in relative.parts):
                    continue
                if path.suffix.lower() not in {".py", ".yaml", ".yml"}:
                    continue
                validate_relative(relative)
                entries[relative.as_posix()] = (path, "source")

    for relative in sorted(referenced_figure_files(project_root)):
        add_file(entries, project_root, relative, "figure")
    for relative in RESULT_FILES:
        category = "result_metadata" if relative.endswith(".json") else "result_csv"
        add_file(entries, project_root, relative, category)

    validate_public_references(project_root, entries)
    forbidden_names = {
        Path(relative).name
        for relative in entries
        if Path(relative).name in FORBIDDEN_RELEASE_DOCUMENTS
    }
    if forbidden_names:
        raise ValueError(
            "release package contains internal documents: "
            + ", ".join(sorted(forbidden_names))
        )
    return entries


def manifest_bytes(records: list[dict[str, str | int]]) -> bytes:
    stream = io.StringIO(newline="")
    writer = csv.DictWriter(
        stream,
        fieldnames=("archive_path", "category", "bytes", "sha256"),
    )
    writer.writeheader()
    writer.writerows(records)
    return stream.getvalue().encode("utf-8")


def zip_info(path: str) -> zipfile.ZipInfo:
    info = zipfile.ZipInfo(path, date_time=(2026, 8, 28, 0, 0, 0))
    info.compress_type = zipfile.ZIP_DEFLATED
    mode = 0o755 if path.endswith(".py") and "/scripts/" in f"/{path}" else 0o644
    info.external_attr = (0o100000 | mode) << 16
    return info


def main() -> None:
    args = parse_args()
    project_root = args.project_root.resolve()
    if args.documents_only and args.output == DEFAULT_OUTPUT:
        args.output = PROJECT_ROOT / "dist" / "imc_ste_documents_release.zip"
    if args.documents_only and args.manifest_output == DEFAULT_MANIFEST_OUTPUT:
        args.manifest_output = PROJECT_ROOT / "dist" / "document_release_manifest.csv"
    if args.documents_only and args.root_name == "imc_ste_challenge":
        args.root_name = "imc_ste_documents"
    output = args.output if args.output.is_absolute() else project_root / args.output
    manifest_output = (
        args.manifest_output
        if args.manifest_output.is_absolute()
        else project_root / args.manifest_output
    )
    if not re.fullmatch(r"[A-Za-z0-9_.-]+", args.root_name):
        raise ValueError("root name may only contain letters, digits, dot, underscore, and dash")

    entries = collect_entries(project_root, documents_only=args.documents_only)
    records: list[dict[str, str | int]] = []
    payloads: list[tuple[str, bytes]] = []
    for relative, (source, category) in sorted(entries.items()):
        data = source.read_bytes()
        archive_path = f"{args.root_name}/{relative}"
        payloads.append((archive_path, data))
        records.append(
            {
                "archive_path": archive_path,
                "category": category,
                "bytes": len(data),
                "sha256": digest_bytes(data),
            }
        )

    package_info = {
        "name": (
            "IMC STE documentation release"
            if args.documents_only
            else "IMC STE Challenge submission"
        ),
        "author": "Xin Su",
        "built_utc": datetime.now(timezone.utc).isoformat(),
        "source_files": len(records),
        "policy": {
            "included": (
                "English paper, release documentation, referenced figures, canonical result tables"
                if args.documents_only
                else "source, configs, tests, English paper, release documentation, referenced figures, canonical result tables"
            ),
            "excluded": "datasets, checkpoints, JSONL logs, caches, drafts, research notes, checklists, intermediate experiments, build outputs",
            "checkpoint_included": False,
        },
        "verification": (
            "validate SHA-256 values in SUBMISSION_MANIFEST.csv"
            if args.documents_only
            else "python scripts/verify_project.py --package-mode"
        ),
    }
    package_info_data = (json.dumps(package_info, indent=2, ensure_ascii=False) + "\n").encode("utf-8")
    package_info_path = f"{args.root_name}/PACKAGE_INFO.json"
    payloads.append((package_info_path, package_info_data))
    records.append(
        {
            "archive_path": package_info_path,
            "category": "package_metadata",
            "bytes": len(package_info_data),
            "sha256": digest_bytes(package_info_data),
        }
    )

    internal_manifest = manifest_bytes(records)
    internal_manifest_path = f"{args.root_name}/SUBMISSION_MANIFEST.csv"
    payloads.append((internal_manifest_path, internal_manifest))
    all_records = records + [
        {
            "archive_path": internal_manifest_path,
            "category": "package_metadata",
            "bytes": len(internal_manifest),
            "sha256": digest_bytes(internal_manifest),
        }
    ]

    total_uncompressed = sum(int(record["bytes"]) for record in all_records)
    if total_uncompressed > args.max_mib * 2**20:
        raise ValueError(
            f"allowlisted payload exceeds {args.max_mib:.1f} MiB: {total_uncompressed / 2**20:.2f} MiB"
        )

    output.parent.mkdir(parents=True, exist_ok=True)
    if output.exists():
        output.unlink()
    with zipfile.ZipFile(output, "w", compression=zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for archive_path, data in sorted(payloads):
            archive.writestr(zip_info(archive_path), data)

    manifest_output.parent.mkdir(parents=True, exist_ok=True)
    manifest_output.write_bytes(manifest_bytes(all_records))
    checksum_path = output.with_suffix(output.suffix + ".sha256")
    checksum_path.write_text(f"{digest_file(output)}  {output.name}\n", encoding="ascii")
    print(
        json.dumps(
            {
                "archive": str(output),
                "archive_bytes": output.stat().st_size,
                "uncompressed_bytes": total_uncompressed,
                "files": len(all_records),
                "manifest": str(manifest_output),
                "sha256": digest_file(output),
            },
            ensure_ascii=False,
        )
    )


if __name__ == "__main__":
    main()
