#!/usr/bin/env python3
"""Run the reproducibility checks used before creating a submission archive."""

from __future__ import annotations

import argparse
import csv
import hashlib
import importlib
import json
import os
import re
import subprocess
import sys
import tempfile
import time
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
REQUIRED_ARTIFACTS = (
    "README.md",
    "README_EN.md",
    "pyproject.toml",
    "environment.yml",
    "docs/algorithm_architecture_and_workflow.md",
    "docs/final_report.md",
    "docs/submission_readme.md",
    "docs/theory_and_complexity.md",
    "docs/generated/key_results.md",
    "docs/figures/submission_key_results.png",
    "docs/figures/efficiency_benchmark.png",
    "docs/figures/optional_full_validation.png",
    "docs/figures/optional_paired_extension.png",
    "paper/main.tex",
    "paper/main.pdf",
    "paper/references.bib",
    "runs/main_uniform_noise_summary.csv",
    "runs/optional_full_validation_summary.csv",
    "runs/optional_paired_extension_summary.csv",
    "runs/optional_full_epoch_extension.csv",
    "runs/efficiency_benchmark.csv",
    "runs/submission_key_results.csv",
)
IMPORTS = ("torch", "torchvision", "numpy", "PIL", "matplotlib", "scipy", "yaml", "imc_ste")
RELEASE_TEXT_FILES = (
    "README.md",
    "README_EN.md",
    "docs/algorithm_architecture_and_workflow.md",
    "docs/final_report.md",
    "docs/submission_readme.md",
    "docs/theory_and_complexity.md",
    "docs/generated/key_results.md",
    "paper/README.md",
    "paper/main.tex",
    "paper/references.bib",
)
FORBIDDEN_RELEASE_DOCUMENTS = {
    "final_report_draft.md",
    "report_notes.md",
    "research_plan.md",
    "submission_checklist.md",
}
FORBIDDEN_RELEASE_MARKERS = (
    "codex",
    "chatgpt",
    "openai",
    "generated by ai",
    "ai-generated",
    "todo",
    "fixme",
    "工作底稿",
    "报告草稿",
    "思考过程",
    "中间思考",
    "作者与所属单位暂时留空",
    "authors and affiliations are intentionally blank",
    "report_notes.md",
    "research_plan.md",
    "submission_checklist.md",
    "final_report_draft.md",
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", type=Path, default=PROJECT_ROOT)
    parser.add_argument("--device", choices=("auto", "cpu", "cuda"), default="cpu")
    parser.add_argument("--expected-tests", type=int, default=48)
    parser.add_argument("--skip-tests", action="store_true")
    parser.add_argument("--skip-smoke", action="store_true")
    parser.add_argument("--skip-rebuild", action="store_true")
    parser.add_argument("--package-mode", action="store_true")
    parser.add_argument(
        "--output",
        type=Path,
        default=PROJECT_ROOT / "runs" / "verification_report.json",
    )
    return parser.parse_args()


def run_command(
    command: list[str], *, cwd: Path, env: dict[str, str]
) -> dict[str, str | int | float]:
    start = time.perf_counter()
    result = subprocess.run(
        command,
        cwd=cwd,
        env=env,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        check=False,
    )
    elapsed = time.perf_counter() - start
    record: dict[str, str | int | float] = {
        "command": " ".join(command),
        "returncode": result.returncode,
        "seconds": elapsed,
        "output": result.stdout.strip(),
    }
    if result.returncode != 0:
        raise RuntimeError(
            f"verification command failed ({result.returncode}): {' '.join(command)}\n{result.stdout}"
        )
    return record


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def check_imports(project_root: Path) -> dict[str, str]:
    src = str(project_root / "src")
    if src not in sys.path:
        sys.path.insert(0, src)
    versions: dict[str, str] = {}
    for module_name in IMPORTS:
        module = importlib.import_module(module_name)
        versions[module_name] = str(getattr(module, "__version__", "available"))
    return versions


def check_artifacts(project_root: Path) -> list[dict[str, str | int]]:
    records: list[dict[str, str | int]] = []
    for relative in REQUIRED_ARTIFACTS:
        path = project_root / relative
        if not path.is_file() or path.stat().st_size == 0:
            raise FileNotFoundError(f"missing or empty required artifact: {relative}")
        records.append(
            {
                "path": relative,
                "bytes": path.stat().st_size,
                "sha256": sha256(path),
            }
        )
    return records


def check_report(project_root: Path) -> dict[str, int]:
    report_path = project_root / "docs" / "final_report.md"
    report = report_path.read_text(encoding="utf-8")
    images = re.findall(r"\(figures/([A-Za-z0-9_.-]+)\)", report)
    missing = [name for name in images if not (project_root / "docs" / "figures" / name).is_file()]
    if missing:
        raise FileNotFoundError("formal report references missing figures: " + ", ".join(missing))
    equation_numbers = [
        int(value)
        for value in re.findall(r"<em>式（(\d+)）</em>", report)
    ]
    expected = list(range(1, 15))
    if equation_numbers != expected:
        raise ValueError(
            f"formal report equation numbers are not contiguous 1-14: {equation_numbers}"
        )
    if "## 待补内容" in report or "报告草稿" in report:
        raise ValueError("formal report still contains draft/TODO markers")
    return {"figures": len(images), "equations": len(equation_numbers)}


def check_release_documents(project_root: Path) -> dict[str, int | str]:
    checked = 0
    for relative in RELEASE_TEXT_FILES:
        path = project_root / relative
        if not path.is_file():
            raise FileNotFoundError(f"missing release document: {relative}")
        folded = path.read_text(encoding="utf-8").casefold()
        matches = [
            marker
            for marker in FORBIDDEN_RELEASE_MARKERS
            if marker.casefold() in folded
        ]
        if matches:
            raise ValueError(
                f"release document contains internal marker(s) in {relative}: "
                + ", ".join(matches)
            )
        checked += 1

    readme = (project_root / "README.md").read_text(encoding="utf-8")
    readme_en = (project_root / "README_EN.md").read_text(encoding="utf-8")
    paper = (project_root / "paper" / "main.tex").read_text(encoding="utf-8")
    if "**作者：Xin Su**" not in readme:
        raise ValueError("Chinese release README does not identify Xin Su as author")
    if "**Author:** Xin Su" not in readme_en:
        raise ValueError("release README does not identify Xin Su as author")
    if r"\author{Xin Su}" not in paper:
        raise ValueError("paper source does not identify Xin Su as author")
    return {"files": checked, "author": "Xin Su"}


def check_package_hygiene(project_root: Path) -> dict[str, int]:
    internal_manifest = project_root / "SUBMISSION_MANIFEST.csv"
    if internal_manifest.is_file():
        with internal_manifest.open(newline="", encoding="utf-8") as handle:
            records = list(csv.DictReader(handle))
        forbidden: list[str] = []
        verified = 0
        for record in records:
            archive_path = Path(record["archive_path"])
            if any(
                part in {"data", "__pycache__", ".pytest_cache", "build", "dist"}
                for part in archive_path.parts
            ) or archive_path.suffix.lower() in {".pt", ".pth", ".ckpt", ".jsonl", ".pyc"} \
                or archive_path.name in FORBIDDEN_RELEASE_DOCUMENTS:
                forbidden.append(record["archive_path"])
                continue
            if len(archive_path.parts) < 2:
                raise ValueError(f"invalid archived path in manifest: {archive_path}")
            local_path = project_root.joinpath(*archive_path.parts[1:])
            if not local_path.is_file():
                raise FileNotFoundError(
                    f"submission manifest entry is missing after extraction: {archive_path}"
                )
            if local_path.stat().st_size != int(record["bytes"]):
                raise ValueError(f"submission file size differs from manifest: {archive_path}")
            if sha256(local_path) != record["sha256"]:
                raise ValueError(f"submission file hash differs from manifest: {archive_path}")
            verified += 1
        if forbidden:
            raise ValueError(
                "submission manifest contains forbidden entries: "
                + ", ".join(forbidden[:5])
            )
        total_bytes = sum(int(record["bytes"]) for record in records)
        if total_bytes > 100 * 2**20:
            raise ValueError(
                f"submission package exceeds 100 MiB: {total_bytes / 2**20:.2f} MiB"
            )
        return {"files": len(records), "bytes": total_bytes, "verified_files": verified}

    forbidden_dirs = [path for path in project_root.rglob("*") if path.is_dir() and path.name in {"data", "__pycache__", ".pytest_cache"}]
    checkpoints = [path for path in project_root.rglob("*") if path.is_file() and path.suffix.lower() in {".pt", ".pth", ".ckpt"}]
    if forbidden_dirs:
        rendered = ", ".join(str(path.relative_to(project_root)) for path in forbidden_dirs[:5])
        raise ValueError(f"submission package contains forbidden cache/data directories: {rendered}")
    if checkpoints:
        rendered = ", ".join(str(path.relative_to(project_root)) for path in checkpoints[:5])
        raise ValueError(f"submission package contains checkpoint files: {rendered}")
    total_bytes = sum(path.stat().st_size for path in project_root.rglob("*") if path.is_file())
    if total_bytes > 100 * 2**20:
        raise ValueError(f"submission package exceeds 100 MiB: {total_bytes / 2**20:.2f} MiB")
    return {"files": sum(1 for path in project_root.rglob("*") if path.is_file()), "bytes": total_bytes}


def main() -> None:
    args = parse_args()
    project_root = args.project_root.resolve()
    output = args.output if args.output.is_absolute() else project_root / args.output
    env = os.environ.copy()
    src = str(project_root / "src")
    env["PYTHONPATH"] = src + (os.pathsep + env["PYTHONPATH"] if env.get("PYTHONPATH") else "")
    commands: list[dict[str, str | int | float]] = []
    started = time.time()

    package_hygiene = check_package_hygiene(project_root) if args.package_mode else None
    versions = check_imports(project_root)
    report_check = check_report(project_root)
    release_documents = check_release_documents(project_root)
    if not args.skip_smoke:
        commands.append(
            run_command(
                [sys.executable, "scripts/smoke_test.py", "--device", args.device],
                cwd=project_root,
                env=env,
            )
        )
    if not args.skip_tests:
        test_record = run_command(
            [sys.executable, "-m", "pytest", "-q"], cwd=project_root, env=env
        )
        match = re.search(r"(\d+) passed", str(test_record["output"]))
        if match is None:
            raise RuntimeError("pytest output did not contain a passed-test count")
        passed = int(match.group(1))
        if passed != args.expected_tests:
            raise RuntimeError(
                f"expected {args.expected_tests} passing tests, observed {passed}"
            )
        test_record["passed"] = passed
        commands.append(test_record)
    if not args.skip_rebuild:
        with tempfile.TemporaryDirectory(prefix="imc_ste_rebuild_") as temp_dir:
            temp_root = Path(temp_dir)
            rebuilt_csv = temp_root / "submission_key_results.csv"
            rebuilt_markdown = temp_root / "key_results.md"
            rebuilt_figure = temp_root / "submission_key_results.png"
            rebuild_record = run_command(
                [
                    sys.executable,
                    "scripts/build_key_results.py",
                    "--output",
                    str(rebuilt_csv),
                    "--markdown-output",
                    str(rebuilt_markdown),
                    "--figure",
                    str(rebuilt_figure),
                ],
                cwd=project_root,
                env=env,
            )
            if rebuilt_csv.read_bytes() != (project_root / "runs" / "submission_key_results.csv").read_bytes():
                raise ValueError("rebuilt key-result CSV differs from the packaged canonical table")
            if rebuilt_markdown.read_bytes() != (project_root / "docs" / "generated" / "key_results.md").read_bytes():
                raise ValueError("rebuilt key-result Markdown differs from the packaged canonical table")
            if not rebuilt_figure.is_file() or rebuilt_figure.stat().st_size == 0:
                raise ValueError("key-result figure rebuild produced no output")
            rebuild_record["csv_sha256"] = sha256(rebuilt_csv)
            rebuild_record["markdown_sha256"] = sha256(rebuilt_markdown)
            rebuild_record["figure_bytes"] = rebuilt_figure.stat().st_size
            commands.append(rebuild_record)

    artifacts = check_artifacts(project_root)
    report = {
        "status": "passed",
        "project_root": str(project_root),
        "python": sys.version.split()[0],
        "imports": versions,
        "report_check": report_check,
        "release_documents": release_documents,
        "commands": commands,
        "artifacts": artifacts,
        "package_hygiene": package_hygiene,
        "started_unix": started,
        "elapsed_seconds": time.time() - started,
    }
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(json.dumps({"status": "passed", "report": str(output), "commands": len(commands)}, ensure_ascii=False))


if __name__ == "__main__":
    main()
