from .convert import (
    activation_scale_regularization_loss,
    activation_scale_summary,
    apply_activation_range_scaling,
    apply_gradient_noise_statistics,
    apply_layerwise_mapping_gains,
    apply_layerwise_mac_tile_sizes,
    apply_layerwise_noise_scales,
    apply_layerwise_read_repeats,
    apply_named_layer_read_repeats,
    apply_output_noise_read_compensation,
    convert_model,
    enable_learnable_activation_scales,
    set_compute_mode,
    set_conv_chunk_rows,
    set_conv_weight_noise_scope,
    set_layer_read_repeats,
    set_read_approximation,
)
from .fold import fold_batchnorms
from .layers import (
    COMPUTE_MODES,
    READ_APPROXIMATION_MODES,
    WEIGHT_NOISE_SCOPES,
    NoisyConv2d,
    NoisyLinear,
)
from .noise import (
    MatmulNoiseState,
    NoiseConfig,
    moment_matched_read_config,
    noisy_grouped_matmul,
    noisy_matmul,
    sample_matmul_noise_state,
    scale_noise_config,
    slice_matmul_noise_state,
)
from .online_profile import (
    ChannelNoiseEstimate,
    OnlineGradientProfile,
    estimate_channel_noise,
)
from .proposal_consistency import ProposalAlignedROIConsistency
from .ste import STEGradientProfile, STE_STRATEGIES, ste_grouped_matmul, ste_matmul
from .task_consistency import (
    TaskOutputConsistency,
    bernoulli_soft_target_kl,
    normalized_smooth_l1,
    soft_target_kl,
)

__all__ = [
    "COMPUTE_MODES",
    "READ_APPROXIMATION_MODES",
    "WEIGHT_NOISE_SCOPES",
    "MatmulNoiseState",
    "NoiseConfig",
    "NoisyConv2d",
    "NoisyLinear",
    "ChannelNoiseEstimate",
    "OnlineGradientProfile",
    "ProposalAlignedROIConsistency",
    "STE_STRATEGIES",
    "STEGradientProfile",
    "TaskOutputConsistency",
    "activation_scale_regularization_loss",
    "activation_scale_summary",
    "apply_activation_range_scaling",
    "apply_gradient_noise_statistics",
    "apply_layerwise_mapping_gains",
    "apply_layerwise_mac_tile_sizes",
    "apply_layerwise_noise_scales",
    "apply_layerwise_read_repeats",
    "apply_named_layer_read_repeats",
    "apply_output_noise_read_compensation",
    "bernoulli_soft_target_kl",
    "convert_model",
    "enable_learnable_activation_scales",
    "estimate_channel_noise",
    "fold_batchnorms",
    "noisy_grouped_matmul",
    "noisy_matmul",
    "normalized_smooth_l1",
    "sample_matmul_noise_state",
    "moment_matched_read_config",
    "scale_noise_config",
    "set_compute_mode",
    "set_conv_chunk_rows",
    "set_conv_weight_noise_scope",
    "set_layer_read_repeats",
    "set_read_approximation",
    "slice_matmul_noise_state",
    "soft_target_kl",
    "ste_grouped_matmul",
    "ste_matmul",
]
